var GETTYSBURG = [
{id:"p1",n:1,text:"Four score and seven years ago our fathers brought forth on this continent a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.",hook:"87 years before 1863",pic:"\ud83d\udcdc",scene:"A rolled parchment and a tiny 1776 flag.",why:"Four score means four twenties — 80 — plus seven is 87. Count back from 1863 and you land on 1776.",gesture:"Hold up four fingers, then seven.",keys:["four","score","seven","fathers","continent","nation","liberty","equal"]},
{id:"p2",n:2,text:"Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure.",hook:"A test the country is taking",pic:"\u2694\ufe0f",scene:"Two toy soldiers across a cracked fence.",why:"Lincoln is asking if a country built on liberty can last when it is fighting itself.",gesture:"Press your palms together, then pull them apart.",keys:["engaged","civil","war","testing","nation","endure"]},
{id:"p3",n:3,text:"We are met on a great battle-field of that war.",hook:"They are standing in the field",pic:"\ud83c\udf3e",scene:"A quiet field with evening gold.",why:"Gettysburg was a real battle three months earlier. The speech happens on that ground.",gesture:"Plant both feet. Point down at the floor.",keys:["met","great","battle","field","war"]},
{id:"p4",n:4,text:"We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live.",hook:"A resting place",pic:"\ud83e\udea8",scene:"A small stone marker under an oak.",why:"They came to set aside a cemetery for the soldiers who died so the country could keep going.",gesture:"Bow your head once, then stand tall.",keys:["dedicate","portion","field","resting","lives","nation"]},
{id:"p5",n:5,text:"It is altogether fitting and proper that we should do this.",hook:"This is the right thing",pic:"\u2713",scene:"A calm nod.",why:"Honoring the dead is simply the right and decent thing to do.",gesture:"One small nod.",keys:["altogether","fitting","proper","should"]},
{id:"p6",n:6,text:"But, in a larger sense, we can not dedicate — we can not consecrate — we can not hallow — this ground.",hook:"Words cannot make the ground holy",pic:"\ud83c\udf0d",scene:"Hands open over the dirt.",why:"Dedicate, consecrate, and hallow mean make this place special. Lincoln says our words are too small for that.",gesture:"Open both hands, then drop them.",keys:["larger","sense","dedicate","consecrate","hallow","ground"]},
{id:"p7",n:7,text:"The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract.",hook:"The soldiers already did it",pic:"\ud83d\udee1\ufe0f",scene:"A shield leaning on a tree.",why:"The people who fought here already made the ground sacred.",gesture:"Hand on heart, then point to the field.",keys:["brave","living","dead","struggled","consecrated"]},
{id:"p8",n:8,text:"The world will little note, nor long remember what we say here, but it can never forget what they did here.",hook:"Deeds last longer than speeches",pic:"\ud83d\udd4a\ufe0f",scene:"A bird lifting off a fence post.",why:"Lincoln thought the speech would be forgotten. The soldiers’ courage is the main thing.",gesture:"Tap your lips, then tap your heart.",keys:["world","note","remember","say","forget","did"]},
{id:"p9",n:9,text:"It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced.",hook:"The living still have work",pic:"\ud83d\udee0\ufe0f",scene:"A hammer and a half-built wall.",why:"The soldiers started a job. People still alive have to finish it.",gesture:"Roll up one sleeve.",keys:["living","dedicated","unfinished","work","fought"]},
{id:"p10",n:10,text:"It is rather for us to be here dedicated to the great task remaining before us —",hook:"A job still in front of us",pic:"\ud83c\udf04",scene:"A path over a low hill.",why:"The great task is keeping liberty and equality actually going.",gesture:"Point forward down the path.",keys:["rather","dedicated","great","task","remaining"]},
{id:"p11",n:11,text:"that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion —",hook:"They gave everything",pic:"\ud83d\udc9b",scene:"A small gold heart on a stone.",why:"The last full measure of devotion means they gave their whole lives.",gesture:"Both hands offer something forward.",keys:["honored","dead","devotion","cause","last","measure"]},
{id:"p12",n:12,text:"that we here highly resolve that these dead shall not have died in vain — that this nation, under God, shall have a new birth of freedom — and that government of the people, by the people, for the people, shall not perish from the earth.",hook:"Of, by, and for the people",pic:"\ud83d\uddfd",scene:"Three open doors to the same light.",why:"In vain means for nothing. Lincoln asks us to make sure the deaths meant something.",gesture:"Open arms wide on of, by, and for the people.",keys:["resolve","vain","nation","freedom","government","people","perish"]}
];
var PREAMBLE = [
{id:"p1",n:1,text:"We the People of the United States,",hook:"Who is speaking",pic:"\ud83d\udc65",scene:"Neighbors standing together, not a king.",why:"The Constitution starts with the people, not a ruler.",gesture:"Point to yourself, then sweep toward everyone.",keys:["we","people","united","states"]},
{id:"p2",n:2,text:"in Order to form a more perfect Union,",hook:"A better together",pic:"\ud83d\udd17",scene:"Thirteen sticks tied into one bundle.",why:"More perfect means keep making the country work better together.",gesture:"Hook your fingers together.",keys:["order","form","more","perfect","union"]},
{id:"p3",n:3,text:"establish Justice, insure domestic Tranquility,",hook:"Fair and peaceful at home",pic:"\u2696\ufe0f",scene:"A small scale next to a quiet house.",why:"Justice means fair rules. Domestic Tranquility means peace inside the country.",gesture:"Hold palms like a scale, then rest them flat.",keys:["establish","justice","insure","domestic","tranquility"]},
{id:"p4",n:4,text:"provide for the common defence,",hook:"Keep the country safe",pic:"\ud83d\udee1\ufe0f",scene:"A shield big enough for many people.",why:"Common defence means we protect the whole country together.",gesture:"Raise one arm like a shield.",keys:["provide","common","defence","defense"]},
{id:"p5",n:5,text:"promote the general Welfare,",hook:"Help people flourish",pic:"\ud83c\udf3e",scene:"A shared table with bread.",why:"General welfare means the well-being of the people as a whole.",gesture:"Open both hands as if offering a meal.",keys:["promote","general","welfare"]},
{id:"p6",n:6,text:"and secure the Blessings of Liberty to ourselves and our Posterity,",hook:"Freedom for kids not born yet",pic:"\ud83d\udd4a\ufe0f",scene:"An adult hands a lantern to a child.",why:"Posterity means the people who come after us.",gesture:"Hand an invisible lantern forward.",keys:["secure","blessings","liberty","posterity"]},
{id:"p7",n:7,text:"do ordain and establish this Constitution for the United States of America.",hook:"This is the rulebook",pic:"\ud83d\udcdc",scene:"A book of rules on a table everyone can see.",why:"Ordain and establish means we make this the official plan.",gesture:"Set both hands down as if placing a heavy book.",keys:["ordain","establish","constitution","america"]}
];
var TOPICS = [
{id:"gettysburg",title:"Gettysburg Address",short:"Gettysburg",kicker:"Twelve lanterns on the field",blurb:"Lincoln\u2019s short speech. Hear it, hide it, say it.",ready:true,lastFirstOk:true,introDefault:["p3","p5","p1"],introLastFirst:["p6","p7","p8","p12","p11","p10","p9","p3","p5","p4","p2","p1"],phrases:GETTYSBURG},
{id:"preamble",title:"Preamble",short:"Preamble",kicker:"We the People",blurb:"The opening of the Constitution. Seven short lanterns.",ready:true,lastFirstOk:false,introDefault:["p1","p2","p7"],introLastFirst:["p7","p6","p1","p2","p3","p4","p5"],phrases:PREAMBLE}
];
function topicById(id){ for (var i=0;i<TOPICS.length;i++) if (TOPICS[i].id===id) return TOPICS[i]; return TOPICS[0]; }
function currentTopic(){ var id=(typeof getFun==="function" && getFun().topic) || "gettysburg"; return topicById(id); }
function currentPhrases(){ return currentTopic().phrases; }
var PHRASES = GETTYSBURG;
var INTRO_DEFAULT = TOPICS[0].introDefault;
var INTRO_LAST_FIRST = TOPICS[0].introLastFirst;
function phraseById(id){ var list=currentPhrases(); for (var i=0;i<list.length;i++) if (list[i].id===id) return list[i]; return null; }
